import express from "express";
import cors from "cors";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import dotenv from "dotenv";
import {products} from "./data.js";
dotenv.config();
const app=express(), PORT=process.env.PORT||5000, JWT_SECRET=process.env.JWT_SECRET||"quickcart-demo-secret";
app.use(cors({origin:"*",methods:["GET","POST","PUT","DELETE","PATCH","OPTIONS"]}));
app.use(express.json());
const users=[{id:1,name:"QuickCart Admin",email:"admin@quickcart.local",password:bcrypt.hashSync("QuickCart@123",10),role:"admin"}];
const carts=new Map(),orders=[];
const tokenFor=u=>jwt.sign({id:u.id,email:u.email,name:u.name,role:u.role},JWT_SECRET,{expiresIn:"7d"});
const auth=(req,res,next)=>{try{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({message:"Login required"});req.user=jwt.verify(h.slice(7),JWT_SECRET);next()}catch{return res.status(401).json({message:"Invalid or expired token"})}};
const getCart=u=>{const ids=carts.get(u.id)||{};return Object.entries(ids).map(([id,qty])=>{const p=products.find(x=>x.id===+id);return p?{...p,qty:+qty,lineTotal:p.price*qty}:null}).filter(Boolean)};
app.get("/api/health",(req,res)=>res.json({ok:true,service:"QuickCart API",time:new Date().toISOString()}));
app.get("/api/products",(req,res)=>{let out=[...products];const{q,category,sort}=req.query;if(q)out=out.filter(p=>p.name.toLowerCase().includes(q.toLowerCase()));if(category&&category!=="All")out=out.filter(p=>p.category===category);if(sort==="price-low")out.sort((a,b)=>a.price-b.price);if(sort==="price-high")out.sort((a,b)=>b.price-a.price);res.json(out)});
app.get("/api/categories",(req,res)=>res.json(["All",...new Set(products.map(p=>p.category))]));
app.post("/api/auth/register",async(req,res)=>{const{name,email,password}=req.body||{};if(!name||!email||!password)return res.status(400).json({message:"Name, email and password are required"});if(users.some(u=>u.email===email.toLowerCase()))return res.status(409).json({message:"Email already registered"});const u={id:users.length+1,name,email:email.toLowerCase(),password:await bcrypt.hash(password,10),role:"customer"};users.push(u);res.json({token:tokenFor(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.post("/api/auth/login",async(req,res)=>{const{email,password}=req.body||{},u=users.find(x=>x.email===String(email||"").toLowerCase());if(!u||!(await bcrypt.compare(password||"",u.password)))return res.status(401).json({message:"Invalid email or password"});res.json({token:tokenFor(u),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get("/api/me",auth,(req,res)=>res.json(req.user));
app.get("/api/cart",auth,(req,res)=>res.json(getCart(req.user)));
app.put("/api/cart/:productId",auth,(req,res)=>{const p=products.find(x=>x.id===+req.params.productId),qty=Math.max(0,Math.min(20,Number(req.body.qty)||0));if(!p)return res.status(404).json({message:"Product not found"});const c=carts.get(req.user.id)||{};if(qty)c[p.id]=qty;else delete c[p.id];carts.set(req.user.id,c);res.json(getCart(req.user))});
app.delete("/api/cart",auth,(req,res)=>{carts.delete(req.user.id);res.json([])});
app.post("/api/orders",auth,(req,res)=>{const items=getCart(req.user);if(!items.length)return res.status(400).json({message:"Cart is empty"});for(const x of items){const p=products.find(p=>p.id===x.id);if(x.qty>p.stock)return res.status(400).json({message:p.name+" is out of stock"})}const subtotal=items.reduce((s,x)=>s+x.lineTotal,0),delivery=subtotal>=499?0:35,handling=subtotal?4:0;items.forEach(x=>products.find(p=>p.id===x.id).stock-=x.qty);const order={id:1000+orders.length+1,userId:req.user.id,items,subtotal,delivery,handling,total:subtotal+delivery+handling,status:"Confirmed",createdAt:new Date().toISOString()};orders.push(order);carts.delete(req.user.id);res.status(201).json(order)});
app.get("/api/orders",auth,(req,res)=>res.json(orders.filter(o=>o.userId===req.user.id).sort((a,b)=>b.id-a.id)));
app.get("/api/admin/stats",auth,(req,res)=>{if(req.user.role!=="admin")return res.status(403).json({message:"Admin only"});res.json({products:products.length,users:users.length,orders:orders.length,revenue:orders.reduce((s,o)=>s+o.total,0)})});
app.get("/api/admin/orders",auth,(req,res)=>{if(req.user.role!=="admin")return res.status(403).json({message:"Admin only"});res.json(orders)});
app.patch("/api/admin/orders/:id",auth,(req,res)=>{if(req.user.role!=="admin")return res.status(403).json({message:"Admin only"});const o=orders.find(x=>x.id===+req.params.id);if(!o)return res.status(404).json({message:"Order not found"});o.status=req.body.status||o.status;res.json(o)});
app.listen(PORT,()=>console.log("QuickCart API running on "+PORT));
