import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import "./style.css";

const API=import.meta.env.VITE_API_URL||"http://localhost:5000/api";
async function api(path,opt={}){const token=localStorage.getItem("qc_token");const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||"Request failed");return d}

function App(){
 const [products,setProducts]=useState([]),[cats,setCats]=useState([]),[cat,setCat]=useState("All"),[q,setQ]=useState(""),[sort,setSort]=useState(""),[cart,setCart]=useState([]),[user,setUser]=useState(null),[modal,setModal]=useState(null),[toast,setToast]=useState(""),[loading,setLoading]=useState(true);
 const [orders,setOrders]=useState([]),[admin,setAdmin]=useState(null),[selected,setSelected]=useState(null),[form,setForm]=useState({name:"",email:"",password:""}),[address,setAddress]=useState({name:"",phone:"",line:"",city:"Delhi",pin:""});
 const [wish,setWish]=useState(()=>JSON.parse(localStorage.getItem("qc_wishlist")||"[]"));
 const total=useMemo(()=>cart.reduce((s,x)=>s+x.lineTotal,0),[cart]),delivery=total>=499||!total?0:35,grand=total+delivery+(total?4:0),count=cart.reduce((s,x)=>s+x.qty,0);
 useEffect(()=>{localStorage.setItem("qc_wishlist",JSON.stringify(wish))},[wish]);
 useEffect(()=>{api("/categories").then(setCats).catch(()=>{});load()},[cat,q,sort]);
 useEffect(()=>{if(localStorage.getItem("qc_token"))Promise.all([api("/me"),api("/cart")]).then(([u,c])=>{setUser(u);setCart(c)}).catch(()=>localStorage.removeItem("qc_token"))},[]);
 async function load(){setLoading(true);try{const p=new URLSearchParams({category:cat==="Wishlist"?"All":cat,q,sort});setProducts(await api("/products?"+p))}catch(e){notify(e.message)}finally{setLoading(false)}}
 function notify(x){setToast(x);setTimeout(()=>setToast(""),2200)}
 async function add(p,d=1){if(!user){setModal("login");return}const old=cart.find(x=>x.id===p.id)?.qty||0;try{setCart(await api("/cart/"+p.id,{method:"PUT",body:JSON.stringify({qty:Math.max(0,old+d)})}));if(d>0)notify("Added to cart")}catch(e){notify(e.message)}}
 function toggle(id){setWish(w=>w.includes(id)?w.filter(x=>x!==id):[...w,id]);notify(wish.includes(id)?"Removed from wishlist":"Saved to wishlist")}
 async function auth(e,reg){e.preventDefault();try{const d=await api(reg?"/auth/register":"/auth/login",{method:"POST",body:JSON.stringify(form)});localStorage.setItem("qc_token",d.token);setUser(d.user);setCart(await api("/cart"));setModal(null);setForm({name:"",email:"",password:""});notify("Welcome to QuickCart!")}catch(e){notify(e.message)}}
 async function checkout(){if(!address.name||!address.phone||!address.line||!address.pin){notify("Complete your delivery address");return}if(!/^[0-9]{10}$/.test(address.phone)||!/^[0-9]{6}$/.test(address.pin)){notify("Enter valid phone and PIN");return}try{const o=await api("/orders",{method:"POST",body:JSON.stringify({address,paymentMethod:"COD"})});setCart([]);setModal({ok:true,order:o});notify("Order placed")}catch(e){notify(e.message)}}
 async function showOrders(){try{setOrders(await api("/orders"));setModal("orders")}catch(e){notify(e.message)}}
 async function showAdmin(){try{const [stats,os]=await Promise.all([api("/admin/stats"),api("/admin/orders")]);setAdmin({stats,orders:os});setModal("admin")}catch(e){notify(e.message)}}
 async function status(id,s){try{await api("/admin/orders/"+id,{method:"PATCH",body:JSON.stringify({status:s})});await showAdmin();notify("Status updated")}catch(e){notify(e.message)}}
 function logout(){localStorage.removeItem("qc_token");setUser(null);setCart([]);setModal(null);notify("Logged out")}
 const wishlistProducts=products.filter(p=>wish.includes(p.id));
 return <>
 <div className="top">⚡ Free delivery above ₹499 <span>Fresh groceries • Fast delivery • Secure checkout</span></div>
 <header><div className="logo">Quick<span>Cart</span><small>GROCERIES IN MINUTES</small></div><div className="location">📍 <b>Delhi</b><small>Deliver to your location</small></div><div className="search">⌕<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search groceries, fruits, snacks..."/></div><button className="account" onClick={()=>setModal(user?"account":"login")}>👤 {user?user.name.split(" ")[0]:"Login"}</button><button className="cartbtn" onClick={()=>setModal("cart")}>🛒 ₹{total}<i>{count}</i></button></header>
 <nav>{cats.map(c=><button key={c} className={cat===c?"active":""} onClick={()=>setCat(c)}>{c}</button>)}<button className={cat==="Wishlist"?"active":""} onClick={()=>setCat("Wishlist")}>♡ Wishlist {wish.length?"("+wish.length+")":""}</button><select value={sort} onChange={e=>setSort(e.target.value)}><option value="">Sort</option><option value="price-low">Price: Low to High</option><option value="price-high">Price: High to Low</option></select></nav>
 <main><section className="hero"><div><label>DAILY ESSENTIALS, DELIVERED FAST</label><h1>Your everyday groceries.<br/><em>Right at your door.</em></h1><p>Fresh produce, pantry staples, dairy, snacks and beverages — everything you need in one quick cart.</p><button onClick={()=>document.getElementById("products").scrollIntoView({behavior:"smooth"})}>Shop groceries →</button></div><div className="heroart">🛒🥦🍎🥛🍪</div></section>
 <div className="trust"><div>⚡ <b>Fast delivery</b><small>Quick & convenient</small></div><div>🌿 <b>Fresh quality</b><small>Handpicked products</small></div><div>🔒 <b>Secure checkout</b><small>Protected account</small></div><div>💚 <b>Easy ordering</b><small>Shop in seconds</small></div></div>
 <section id="products"><div className="sectionhead"><div><label>{cat==="Wishlist"?"YOUR SAVED ITEMS":"SHOP BY CATEGORY"}</label><h2>{cat==="Wishlist"?"Wishlist":"Fresh picks for you"}</h2></div><span>{cat==="Wishlist"?wishlistProducts.length:products.length} products</span></div>
 {loading?<div className="loading">Loading fresh products…</div>:cat==="Wishlist"?(wishlistProducts.length?<div className="grid">{wishlistProducts.map(p=><Card key={p.id} p={p} wished toggle={toggle} open={()=>{setSelected(p);setModal("product")}} add={add}/>)}</div>:<div className="empty wide">♡<h3>Your wishlist is empty</h3><p>Tap the heart on a product to save it for later.</p></div>):<div className="grid">{products.map(p=><Card key={p.id} p={p} wished={wish.includes(p.id)} toggle={toggle} open={()=>{setSelected(p);setModal("product")}} add={add}/>)}</div>}
 </section></main><footer><div className="logo">Quick<span>Cart</span></div><p>Groceries made simple. Built for fast everyday shopping.</p><div>© 2026 QuickCart</div></footer>{toast&&<div className="toast">✓ {toast}</div>}
 {modal&&<div className="overlay" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}>
 {modal==="login"||modal==="register"?<Auth type={modal} form={form} setForm={setForm} submit={auth} close={()=>setModal(null)}/>:
 modal==="cart"?<Cart cart={cart} total={total} delivery={delivery} grand={grand} add={add} next={()=>setModal("checkout")} close={()=>setModal(null)}/>:
 modal==="checkout"?<Checkout address={address} setAddress={setAddress} grand={grand} place={checkout} back={()=>setModal("cart")}/>:
 modal==="orders"?<Orders orders={orders} close={()=>setModal(null)}/>:
 modal==="account"?<Account user={user} orders={showOrders} admin={showAdmin} logout={logout} close={()=>setModal(null)}/>:
 modal==="admin"?<Admin data={admin} status={status} close={()=>setModal(null)}/>:
 modal==="product"?<Product p={selected} wished={wish.includes(selected.id)} toggle={toggle} add={add} close={()=>setModal(null)}/>:
 modal&&modal.ok?<><div className="success">✓</div><h2>Order confirmed!</h2><p>Order <b>#{modal.order.id}</b> is confirmed. Pay on delivery.</p><div className="summary orderdetails"><p>Order ID <b>#{modal.order.id}</b></p><p>Status <b>Confirmed</b></p><p>Delivery to <b>{modal.order.address?.name}, {modal.order.address?.phone}</b></p><p>{modal.order.address?.line}, {modal.order.address?.city} - {modal.order.address?.pin}</p><p><b>Items</b></p>{(modal.order.items||[]).map(x=><div key={x.id}><span>{x.name} × {x.qty}</span> <b>₹{x.lineTotal}</b></div>)}<h3>Total <b>₹{modal.order.total}</b></h3><small>Payment: Cash on Delivery</small>{modal.order.sms?.sent&&<small className="smsok">✓ SMS sent to {modal.order.address?.phone}</small>}{modal.order.sms?.reason==="not_configured"&&<small className="smsnote">SMS notification is ready but the provider is not configured yet.</small>}</div><button className="primary" onClick={()=>{setModal(null);showOrders()}}>View all orders</button></>:null}
 </div></div>}</>
}

function Card({p,wished,toggle,open,add}){return <article className="card"><div className="pic" onClick={open}>{p.icon}<small>IN STOCK</small><button className={"heart "+(wished?"liked":"")} onClick={e=>{e.stopPropagation();toggle(p.id)}}>{wished?"♥":"♡"}</button></div><div className="cat">{p.category}</div><h3 onClick={open}>{p.name}</h3><div className="buy"><b>₹{p.price}</b><button onClick={()=>add(p)}>+ Add</button></div></article>}
function Auth({type,form,setForm,submit,close}){return <><button className="x" onClick={close}>×</button><h2>{type==="login"?"Welcome back":"Create your account"}</h2><p>{type==="login"?"Login to continue shopping":"Join QuickCart in seconds"}</p><form onSubmit={e=>submit(e,type==="register")}>{type==="register"&&<input required placeholder="Full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/>}<input required type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="6" type="password" placeholder="Password (min 6)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary" type="submit">{type==="login"?"Login":"Create account"}</button></form></>}
function Cart({cart,total,delivery,grand,add,next,close}){return <><button className="x" onClick={close}>×</button><h2>Your cart</h2>{cart.length?<>{cart.map(x=><div className="cartrow" key={x.id}><span>{x.icon} {x.name}</span><div><button onClick={()=>add(x,-1)}>−</button> {x.qty} <button onClick={()=>add(x,1)}>+</button></div><b>₹{x.lineTotal}</b></div>)}<div className="summary"><p>Subtotal <b>₹{total}</b></p><p>Delivery <b>{delivery?"₹35":"FREE"}</b></p><p>Handling <b>₹4</b></p><h3>Total <b>₹{grand}</b></h3>{total<499&&<small>Add ₹{499-total} more for free delivery.</small>}</div><button className="primary" onClick={next}>Proceed to checkout →</button></>:<div className="empty">🛒<h3>Your cart is empty</h3></div>}</>}
function Checkout({address,setAddress,grand,place,back}){const f=(k,v)=>setAddress({...address,[k]:v});return <><button className="x" onClick={back}>×</button><h2>Secure checkout</h2><p>Delivery details</p><input placeholder="Full name" value={address.name} onChange={e=>f("name",e.target.value)}/><input inputMode="numeric" maxLength="10" placeholder="10-digit phone" value={address.phone} onChange={e=>f("phone",e.target.value.replace(/\D/g,""))}/><input placeholder="House / street / landmark" value={address.line} onChange={e=>f("line",e.target.value)}/><div className="twocol"><input placeholder="City" value={address.city} onChange={e=>f("city",e.target.value)}/><input inputMode="numeric" maxLength="6" placeholder="PIN code" value={address.pin} onChange={e=>f("pin",e.target.value.replace(/\D/g,""))}/></div><div className="paybox">💵 <b>Cash on Delivery</b><small>Pay when your groceries arrive</small></div><div className="summary"><h3>Payable <b>₹{grand}</b></h3></div><button className="primary" onClick={place}>Place order • ₹{grand}</button></>}
function Orders({orders,close}){return <><button className="x" onClick={close}>×</button><h2>Order history</h2>{orders.length?orders.map(o=><div className="order" key={o.id}><div><b>Order #{o.id}</b><small>{new Date(o.createdAt).toLocaleString()}</small></div><span>{o.status}</span><strong>₹{o.total}</strong></div>):<div className="empty">📦<h3>No orders yet</h3></div>}</>}
function Account({user,orders,admin,logout,close}){return <><button className="x" onClick={close}>×</button><div className="avatar">{user.name[0]}</div><h2>Hi, {user.name} 👋</h2><p>{user.email}</p><button className="primary" onClick={orders}>📦 My orders</button>{user.role==="admin"&&<button className="secondary" onClick={admin}>⚙ Admin dashboard</button>}<button className="link" onClick={logout}>Logout</button></>}
function Product({p,wished,toggle,add,close}){return <><button className="x" onClick={close}>×</button><div className="detailpic">{p.icon}</div><div className="cat">{p.category}</div><h2>{p.name}</h2><p>Fresh quality grocery item, ready for quick delivery.</p><div className="detailprice">₹{p.price}</div><div className="detailactions"><button className="secondary" onClick={()=>toggle(p.id)}>{wished?"♥ Saved":"♡ Save"}</button><button className="primary" onClick={()=>{add(p);close()}}>Add to cart</button></div></>}
function Admin({data,status,close}){return <><button className="x" onClick={close}>×</button><h2>Admin dashboard</h2><p>QuickCart store overview</p>{data&&<div className="stats"><div><b>{data.stats.products}</b><small>Products</small></div><div><b>{data.stats.users}</b><small>Customers</small></div><div><b>{data.stats.orders}</b><small>Orders</small></div><div><b>₹{data.stats.revenue}</b><small>Revenue</small></div></div>}<h3>Recent orders</h3>{data?.orders?.length?data.orders.slice().reverse().slice(0,10).map(o=><div className="adminorder" key={o.id}><div><b>#{o.id}</b><small>₹{o.total} • {new Date(o.createdAt).toLocaleDateString()}</small></div><select value={o.status} onChange={e=>status(o.id,e.target.value)}><option>Confirmed</option><option>Packed</option><option>Out for delivery</option><option>Delivered</option><option>Cancelled</option></select></div>):<p>No orders yet.</p>}</>}
createRoot(document.getElementById("root")).render(<App/>);